%%-*- mode: erlang -*-
case os:getenv("HOCON_ESCRIPT") =:= "true" of
    true ->
        %% building escript, delete the post hook
        lists:keydelete(post_hooks, 1, CONFIG);
    false ->
        PostHooks = {post_hooks, [ {"(linux|darwin|solaris|win32)", compile, "make es"}
                                 , {"(freebsd|netbsd|openbsd)", compile, "gmake es"}]},
        [PostHooks | CONFIG]
end.
