-file("/usr/local/Cellar/erlang/22.2/lib/erlang/lib/parsetools-2.1.8/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(hocon_scanner).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.xrl", 92).

identifier("include", TokenLine)  -> {directive, TokenLine, 'include'};
identifier(TokenChars, TokenLine) -> {atom, TokenLine, list_to_atom(TokenChars)}.

bool("true")  -> true;
bool("false") -> false;
bool("on")    -> true;
bool("off")   -> false.

unquote(Str) -> string:strip(Str, both, $").


-file("/usr/local/Cellar/erlang/22.2/lib/erlang/lib/parsetools-2.1.8/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.erl", 318).
yystate() -> 54.

yystate(61, [123|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 3, Tlen);
yystate(61, [102|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 3, Tlen);
yystate(61, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(61, [64|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(61, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,61};
yystate(60, [66|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(60, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,60};
yystate(59, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 33 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 46 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 91 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 97 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [C|Ics], Line, Tlen, Action, Alen) when C >= 99, C =< 101 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [C|Ics], Line, Tlen, Action, Alen) when C >= 103, C =< 109 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [C|Ics], Line, Tlen, Action, Alen) when C >= 111, C =< 113 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [C|Ics], Line, Tlen, Action, Alen) when C >= 118, C =< 8231 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, [C|Ics], Line, Tlen, Action, Alen) when C >= 8234 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(59, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,59};
yystate(58, [160|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 0, Tlen);
yystate(58, [32|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 0, Tlen);
yystate(58, [11|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 0, Tlen);
yystate(58, [12|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 0, Tlen);
yystate(58, [9|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 0, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,58};
yystate(57, [92|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 6, Tlen);
yystate(57, [34|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 6, Tlen);
yystate(57, [11|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 6, Tlen);
yystate(57, [12|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 6, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(50, Ics, Line, Tlen+1, 6, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 33 ->
    yystate(50, Ics, Line, Tlen+1, 6, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(50, Ics, Line, Tlen+1, 6, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 93, C =< 8231 ->
    yystate(50, Ics, Line, Tlen+1, 6, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 8234 ->
    yystate(50, Ics, Line, Tlen+1, 6, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,57};
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(56, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,56};
yystate(55, [123|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 3, Tlen);
yystate(55, [97|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 3, Tlen);
yystate(55, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(55, [64|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(55, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,55};
yystate(54, [160|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 101 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 103, C =< 110 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 112, C =< 115 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 117, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(54, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,54};
yystate(53, [123|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 3, Tlen);
yystate(53, [110|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 3, Tlen);
yystate(53, [102|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 3, Tlen);
yystate(53, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(53, [64|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(53, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 109 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,53};
yystate(52, [101|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 5, Tlen);
yystate(52, [69|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 5, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 5, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,52};
yystate(51, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line};
yystate(50, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 33 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 8231 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 8234 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(50, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,50};
yystate(49, [34|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 6, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,49};
yystate(48, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(47, [123|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 3, Tlen);
yystate(47, [108|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 3, Tlen);
yystate(47, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(47, [64|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(47, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,47};
yystate(46, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(45, [123|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 2, Tlen);
yystate(45, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 2, Tlen);
yystate(45, [64|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 2, Tlen);
yystate(45, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 2, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 2, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 2, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,45};
yystate(44, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(44, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(44, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(44, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,44};
yystate(43, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 33 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 47 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 71, C =< 91 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 96 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 103, C =< 8231 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 8234 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(43, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,43};
yystate(42, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line+1, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(42, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,42};
yystate(41, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line+1, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 47 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 71, C =< 91 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 96 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 103 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(41, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,41};
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 5, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,40};
yystate(39, [123|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 3, Tlen);
yystate(39, [115|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 3, Tlen);
yystate(39, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(39, [64|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(39, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,39};
yystate(38, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(37, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line+1, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 47 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Tlen, Action, Alen) when C >= 71, C =< 91 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 96 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(37, [C|Ics], Line, Tlen, Action, Alen) when C >= 103 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(37, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,37};
yystate(36, [115|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 9, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,36};
yystate(35, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 33 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 47 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 71, C =< 91 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 96 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 103, C =< 8231 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 8234 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(35, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,35};
yystate(34, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line+1, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 35 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(34, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,34};
yystate(33, [123|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 3, Tlen);
yystate(33, [117|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 3, Tlen);
yystate(33, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(33, [64|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(33, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,33};
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(32, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,32};
yystate(31, [123|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 3, Tlen);
yystate(31, [101|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 3, Tlen);
yystate(31, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(31, [64|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(31, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,31};
yystate(30, [123|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 3, Tlen);
yystate(30, [114|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 3, Tlen);
yystate(30, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(30, [64|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(30, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,30};
yystate(29, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line+1, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 47 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 71, C =< 91 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 96 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 103 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(29, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,29};
yystate(28, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(28, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,28};
yystate(27, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 33 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 47 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 71, C =< 91 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 96 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 103, C =< 8231 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 8234 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(27, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,27};
yystate(26, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line+1, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 35 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(26, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,26};
yystate(25, [123|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 3, Tlen);
yystate(25, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(25, [64|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(25, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,25};
yystate(24, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(24, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,24};
yystate(23, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(22, [68|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(22, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,22};
yystate(21, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line+1, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 47 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 71, C =< 91 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 96 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 103 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(21, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,21};
yystate(20, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line};
yystate(19, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 33 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 47 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [C|Ics], Line, Tlen, Action, Alen) when C >= 71, C =< 91 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 96 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [C|Ics], Line, Tlen, Action, Alen) when C >= 103, C =< 8231 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [C|Ics], Line, Tlen, Action, Alen) when C >= 8234 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(19, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,19};
yystate(18, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line};
yystate(17, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(17, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,17};
yystate(16, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(15, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(14, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(14, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,14};
yystate(13, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line+1, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(13, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,13};
yystate(12, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(12, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,12};
yystate(11, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 33 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 8231 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 8234 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(11, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,11};
yystate(10, [34|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [10|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line+1, Tlen+1, 7, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(42, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(42, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 35 ->
    yystate(42, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,10};
yystate(9, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(9, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,9};
yystate(8, [117|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [115|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [110|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [109|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [104|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [100|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [77|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [75|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [71|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [46|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,8};
yystate(7, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(6, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(6, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,6};
yystate(5, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line+1, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 46 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 91 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 97 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 99, C =< 101 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 103, C =< 109 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 111, C =< 113 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 118 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(5, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,5};
yystate(4, [46|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 4, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(4, Ics, Line, Tlen+1, 4, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,4};
yystate(3, [11|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 1, Tlen);
yystate(3, [12|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 1, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(3, Ics, Line, Tlen+1, 1, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 8231 ->
    yystate(3, Ics, Line, Tlen+1, 1, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 8234 ->
    yystate(3, Ics, Line, Tlen+1, 1, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,3};
yystate(2, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line+1, Tlen+1, Action, Alen);
yystate(2, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [C|Ics], Line, Tlen, Action, Alen) when C >= 35 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(2, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,2};
yystate(1, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(1, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,1};
yystate(0, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, _) ->
    yyaction_0();
yyaction(1, _, _, _) ->
    yyaction_1();
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, _, _, TokenLine) ->
    yyaction_10(TokenLine);
yyaction(11, _, _, TokenLine) ->
    yyaction_11(TokenLine);
yyaction(12, _, _, TokenLine) ->
    yyaction_12(TokenLine);
yyaction(13, _, _, TokenLine) ->
    yyaction_13(TokenLine);
yyaction(14, _, _, TokenLine) ->
    yyaction_14(TokenLine);
yyaction(15, _, _, TokenLine) ->
    yyaction_15(TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/0}).
-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.xrl", 71).
yyaction_0() ->
     skip_token .

-compile({inline,yyaction_1/0}).
-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.xrl", 72).
yyaction_1() ->
     skip_token .

-compile({inline,yyaction_2/2}).
-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.xrl", 73).
yyaction_2(TokenChars, TokenLine) ->
     { token, { bool, TokenLine, bool (TokenChars) } } .

-compile({inline,yyaction_3/2}).
-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.xrl", 74).
yyaction_3(TokenChars, TokenLine) ->
     { token, identifier (TokenChars, TokenLine) } .

-compile({inline,yyaction_4/2}).
-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.xrl", 75).
yyaction_4(TokenChars, TokenLine) ->
     { token, { integer, TokenLine, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_5/2}).
-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.xrl", 76).
yyaction_5(TokenChars, TokenLine) ->
     { token, { float, TokenLine, list_to_float (TokenChars) } } .

-compile({inline,yyaction_6/2}).
-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.xrl", 77).
yyaction_6(TokenChars, TokenLine) ->
     { token, { string, TokenLine, iolist_to_binary (unquote (TokenChars)) } } .

-compile({inline,yyaction_7/2}).
-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.xrl", 78).
yyaction_7(TokenChars, TokenLine) ->
     { token, { string, TokenLine, iolist_to_binary (unquote (TokenChars)) } } .

-compile({inline,yyaction_8/2}).
-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.xrl", 79).
yyaction_8(TokenChars, TokenLine) ->
     { token, { bytesize, TokenLine, TokenChars } } .

-compile({inline,yyaction_9/2}).
-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.xrl", 80).
yyaction_9(TokenChars, TokenLine) ->
     { token, { duration, TokenLine, TokenChars } } .

-compile({inline,yyaction_10/1}).
-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.xrl", 82).
yyaction_10(TokenLine) ->
     { token, { '{', TokenLine } } .

-compile({inline,yyaction_11/1}).
-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.xrl", 83).
yyaction_11(TokenLine) ->
     { token, { '}', TokenLine } } .

-compile({inline,yyaction_12/1}).
-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.xrl", 84).
yyaction_12(TokenLine) ->
     { token, { '[', TokenLine } } .

-compile({inline,yyaction_13/1}).
-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.xrl", 85).
yyaction_13(TokenLine) ->
     { token, { ']', TokenLine } } .

-compile({inline,yyaction_14/1}).
-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.xrl", 86).
yyaction_14(TokenLine) ->
     { token, { '=', TokenLine } } .

-compile({inline,yyaction_15/1}).
-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.xrl", 87).
yyaction_15(TokenLine) ->
     { token, { ':', TokenLine } } .

-compile({inline,yyaction_16/1}).
-file("/Users/fenglee/Hamler/hocon/src/hocon_scanner.xrl", 88).
yyaction_16(TokenLine) ->
     { token, { ',', TokenLine } } .

-file("/usr/local/Cellar/erlang/22.2/lib/erlang/lib/parsetools-2.1.8/include/leexinc.hrl", 313).
