name: Elvis Linter

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: erlang:22.0.7
    steps:
      - uses: actions/checkout@v1
      - run: |
          ./scripts/elvis-check.sh $GITHUB_BASE_REF
