name: Style Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: erlang:26

    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/elvis-check.sh $GITHUB_BASE_REF
      - run: make erlfmt-check
